#
# ~/.bash_profile
#

[[ -f ~/.bashrc ]] && . ~/.bashrc


export EDITOR=vim
export PATH="$HOME/.cargo/bin:$PATH"
export PATH="$HOME/.local/bin:$PATH"
export DOTS="$HOME/.dots"
export WDIR="/mnt/c/Users/17074"
