#
# ~/.bash_profile
#

[[ -f ~/.bashrc ]] && . ~/.bashrc

# https://wiki.archlinux.org/index.php/XDG_Base_Directory
export XDG_DATA_HOME="$HOME"/.local/share
export XDG_CONFIG_HOME="$HOME"/.config
export XDG_CACHE_HOME="$HOME"/.cache
export XDG_DATA_DIRS=/usr/local/share:/usr/share
export XDG_CONFIG_DIRS=/etc/xdg

# Start the ssh-agent
eval "$(ssh-agent -s)"
# Auto sign git commits
export GPG_TTY=$(tty)

# Rust
# export PATH="/home/rj/.local/share/cargo/bin:$PATH"
export PATH="$HOME/.cargo/bin:$PATH"
export PATH="/usr/local/bin/aarch64-none-elf/bin:$PATH"

export DOTS="$HOME/development/dots"
export PATH="$HOME/tools/hopper/pkg/hopper/opt/hopper-v4/bin:$PATH"
export PATH="/opt/cuda/bin:$PATH"

# Ruby
export PATH="/home/rj/.gem/ruby/2.7.0/bin:$PATH"

# Use the python3 interpreter on your path
export CLOUDSDK_PYTHON=python3
export CLOUDSDK_GSUTIL_PYTHON=python3
export CLOUDSDK_BQ_PYTHON=python3

export GOOGLE_APPLICATION_CREDENTIALS="$HOME/Programs/google-cloud-sdk/project-20200309-0-2169f5f2e217.json"
