export EDITOR=vim
export PATH="$HOME/.cargo/bin:$PATH"
export PATH="$HOME/.local/bin:$PATH"
export PATH="$HOME/.local/bin/nvim/nvim-linux64/bin:$PATH"
export PATH="$HOME/app/rust-analyzer:$PATH"
export PATH="$HOME/app/act-github-actions:$PATH"
export PATH="$HOME/Dev/bitcoin/src:$PATH"
export PATH="$HOME/Dev/cpuminer:$PATH"
export DOTS="$HOME/.dots"

. "$HOME/.cargo/env"
