#
# ~/.bash_profile
#

[[ -f ~/.bashrc ]] && . ~/.bashrc

# https://wiki.archlinux.org/index.php/XDG_Base_Directory
export XDG_DATA_HOME="$HOME"/.local/share
export XDG_CONFIG_HOME="$HOME"/.dots/config
export XDG_CACHE_HOME="$HOME"/.cache

export XDG_DATA_DIRS=/usr/local/share:/usr/share
export XDG_CONFIG_DIRS=/etc/xdg

# export CARGO_HOME="$XDG_DATA_HOME"/cargo
# export RUSTUP_HOME="$XDG_DATA_HOME"/rustup
# export PATH="$XDG_DATA_HOME/.cargo/bin:$PATH"

export PATH="/home/rj/.local/share/cargo/bin:$PATH"
